TrainEndpoint:
  get:
    operationId: train
    summary: train Cruise Control to better model broker cpu usage
    parameters:
      - name: start
        in: query
        description: Timestamp of earlist metrics sample used to train Cruise Control
        schema:
          type: integer
          format: int64
          default: -1
      - name: end
        in: query
        description: Timestamp of latest metrics sample used to train Cruise Control
        schema:
          type: integer
          format: int64
      - name: json
        in: query
        description: Whether to return in JSON format or not
        schema:
          type: boolean
          default: false
    responses:
      '200':
        description: Successful train response
        content:
          application/json:
            schema:
              $ref: '../responses/trainResult.yaml#/TrainResult'
          text/plain:
            schema:
              type: string
      # Response for all errors
      default:
        description: Unexpected error
        content:
          application/json:
            schema:
              $ref: '../responses/errorResponse.yaml#/ErrorResponse'
          text/plain:
            schema:
              type: string
